dictionaries:
  - en
  - en_GB

# Any typos we should ignore?
excluded_words:
  - typoci
  - easyapi  # My project name
  - noqa     # noqa tag for flake8
  - rst      # ReSTructured file
  - md       # Markdown file
  - markdown
  - py       # Python file
  - functools   # python tools for higher-order functions.
