
name: Deploy package to PyPI

on:
  push:
    tags: 
    - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test and build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions setuptools wheel twine
    - name: Run tests with tox
      run: |
        tox -p 4
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

